name: Python CI

on:
  push:
    branches:
      - main # Change this to your main branch if different
  pull_request:
    branches:
      - main # Change this to your main branch if different

jobs:
  lint:
    runs-on: windows-latest # Use Windows for the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest

      - name: Run pylint
        run: |
          pylint app.py model.py tests/test_basic.py  # Adjust paths as needed

  test:
    runs-on: windows-latest # Use Windows for the runner
    needs: lint # Ensure linting is done before running tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run pytest
        run: |
          pytest tests/test_basic.py  # Adjust this path as needed
