name: Python CI

on: [push, pull_request] # Trigger on push and pull request events

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" # Specify the version of Python to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt       # Install packages from requirements.txt

      - name: Run pylint
        run: |
          pylint app.py model.py tests/test_basic.py  # Adjust paths as needed

  test:
    runs-on: windows-latest
    needs: lint # Ensure tests run after linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest tests/test_basic.py
